### ISSUE TITLE
Transformers memory leak?

### ISSUE THREAD

**Issue by fabn** [rgrove/sanitize#129]
I'm using your gem to fix a very badly formatted markup. I'm running the cleaning process in a sidekiq worker and after a while process memory grows with no limit. I (think I have) tracked down the leak to `Sanitize.fragment` call. I made a simple script which should reproduce the issue.

```ruby
200_000.times do |i|
  Sanitize.fragment(raw_markup, Sanitize::Config::WIKIPEDIA)
  if i % 10 == 0
    GC.start
    ending = GC.stat
    puts "#{i} Referenced objects count is: #{ending[:total_allocated_object] - ending[:total_freed_object]}"
    puts "#{i} Current used memory is #{`ps -o rss= -p #{Process.pid}`.to_i / 1024}MB"
    puts ObjectSpace.count_objects
    puts "\n"
  end
end
```

If i run this code on my local machine at iteration 3260 used memory is 813MB and it keeps growing, while other dumped params don't change across iterations. If I use one of the predefined configurations it doesn't happen <sup><a href="#note">1</a></sup>.

Here is my sanitize config 

```ruby
class Sanitize
  module Config
    # Very restrictive config for wikipedia markup sanitizer
    WIKIPEDIA = freeze_config(
        elements: %w[b em i strong u br ol ul li pre p h1 h2 h3 h4 h5 h6],
        remove_contents: %w[sup table],
        # Transformers section
        transformers: [
            # Remove wikipedia edit links
            lambda { |env|
              # Completely remove span.editsection nodes
              if env[:node_name] == 'span' && /editsection/ =~ env[:node][:class]
                env[:node].unlink
              end
            },
            # Remove wikipedia thumb divs i.e. div with some graphic and caption
            lambda { |env|
              if env[:node_name] == 'div' && /thumb/ =~ env[:node][:class]
                env[:node].unlink
              end
            },
        ]
    )
  end
end
```

Here are my current bundle (relevant gems)

```
Gems included by the bundle:
  * crass (1.0.1)
  * nokogiri (1.6.6.2)
  * nokogumbo (1.2.0)
  * sanitize (3.1.1)
```

Full code including the html sample used is available here: https://gist.github.com/fabn/304691f9bd81e1b814cf

<a name="note">(1)</a>: Actually memory usage grows also with `RELAXED` config but very very slowly (i.e. after 4000 iterations used memory is ~70MB while value reported at first iteration was 25MB)

**Comment by rgrove** [comment]
Thanks for the report!

After some initial investigation, it seems like the leak occurs when certain nodes are unlinked, and it appears to be related to Sanitize's [traverse method](https://github.com/rgrove/sanitize/blob/7a43f1d8dc32da10586fa86b4bbc56c04b2dcb1d/lib/sanitize.rb#L237). When I swap that out with Nokogiri's (flawed) traverse method, the leak disappears.

There's nothing obvious in Sanitize's traverse method that seems like it could be leaking memory, but it's possible it could be triggering a leak in Nokogiri. I'll need to dig further.

**Comment by rgrove** [comment]
@fabn I think I've fixed this. Can you try out the dev-3.1.2 branch (or install [this pre-release gem](https://dl.dropboxusercontent.com/u/131998/misc/sanitize-3.1.2.gem)) and let me know if it fixes the leak for you?

**Comment by fabn** [comment]
Thanks for your speedy support.

I tried the same code with dev-3.1.2 branch and it's much better. To give you some numbers at the same iteration I reported earlier memory usage went down from 813MB (in 3.1.1) to 167MB with 3.1.2. So your change makes a great improvement.

However I still see memory growing during time, so there should be some leak in nokogiri itself. I found for instance this report: https://github.com/sparklemotion/nokogiri/issues/1063

**Comment by rgrove** [comment]
Looks like Nokogumbo may be the culprit this time. I can reproduce the leak with this loop, which uses Nokogumbo's HTML5 parser in the same way that `Sanitize.fragment` does:

```ruby
require 'nokogiri'

200_000.times do |i|
  doc = Nokogiri::HTML5.parse("<html><body>#{raw_markup}")
  frag = doc.fragment
  frag << doc.xpath('/html/body/node()')
end
```

However, this loop, which uses Nokogiri's libxml2 parser, doesn't create a leak:

```ruby
require 'nokogiri'

200_000.times do |i|
  doc = Nokogiri::HTML.parse("<html><body>#{raw_markup}")
  frag = doc.fragment
  frag << doc.xpath('/html/body/node()')
end
```

I'll take a look at Nokogumbo and see if I can spot the problem.

**Comment by rgrove** [comment]
@fabn My C-fu isn't strong enough to figure out where this is happening in Nokogumbo, but I've filed an upstream issue for this: https://github.com/rubys/nokogumbo/issues/20

I'll go ahead and close this bug now since the original transformer-related leak is resolved. We can use the Nokogumbo bug to discuss the second leak. Thanks again for the reports and the helpful test cases!

**Comment by fabn** [comment]
Ok, thanks for your help. I'll follow https://github.com/rubys/nokogumbo/issues/20

Just one more question, will you release 3.1.2 or wait for that issue being solved?

**Comment by rgrove** [comment]
Just released 3.1.2. Enjoy!
